### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Keruspe**

### CODE REVIEW

**Comment by djc** [comment]
Presumably we'll want the CI failures resolved before publishing the next release.

**Comment by Keruspe** [comment]
Sure, just posted this as a more constructive way of poking for a release, since tests pass locally.
Will try and give the CI failure a look

**Comment by djc** [comment]
Yeah, looks like a Windows-only failure that's also happening on master.

**Comment by djc** [comment]
Nice!

**Comment by Keruspe** [comment]
So, this is the one that triggered the assert `Native anchor "L=Alvaro Obregon, ST=Distrito Federal, C=MX, postalCode=01030, STREET=Insurgentes Sur 1940, CN=Autoridad Certificadora Raiz de la Secretaria de Economia, OU=Direccion General de Normatividad Mercantil, O=Secretaria de Economia, emailAddress=acrse@economia.gob.mx" is missing from mozilla set`

Now we get a lot more anchors in native windows than mozilla which triggers a new assert (50% more allowed and we hit 151%), not sure what to make of it

**Comment by Keruspe** [comment]
I think it's because of the update to the windows-2019 vm. It might be "normal" with the configuration of this new vm?

@ctz should we maybe relax the max value (maybe just for windows ?) to 1.6 instead of 0.5 (yeah, that's a big bump...)

**Comment by Keruspe** [comment]
I see there are already other specific threshold for windows in other places, let's give it a try

**Comment by Keruspe** [comment]
CI is now green :tada: 

I'll let you judge if that's enough for cutting a new release or if the "fix" just isn't right

**Comment by ctz** [comment]
> @ctz should we maybe relax the max value (maybe just for windows ?) to 1.6 instead of 0.5 (yeah, that's a big bump...)

Yeah that's reasonable. Really, these tests are intended to catch real bugs which might mean that significant numbers of roots are missing or invented. But they're also quite fragile to the various root programs following different update cadences.

**Comment by ctz** [comment]
Thanks!

**Pull request merged**
